### ISSUE TITLE
Monitor

### ISSUE THREAD

**Issue by Infixo** [adaneslavo/More-Unique-Components-for-VP#100]
You can use IsWithinDistanceOfUnitPromotion / IsWithinDistanceOfUnit / IsWithinDistanceOfUnitClass / IsWithinDistanceOfUnitCombatType together with City.
Basically
`bInRange = city:IsWithinDistanceOfUnitPromotion(GameInfoTypes.PROMOTION_UNIT_AMERICA_MONITOR, 1, true, false)
`
does all. Then only set dummy.

**Comment by adaneslavo** [comment]
I though it works only on units. I will try.
