### ISSUE TITLE
Hun luas not working

### ISSUE THREAD

**Issue by pineappledan** [adaneslavo/More-Unique-Components-for-VP#103]
bellum alet - currently it is healing all adjacent units on pillage, including enemies. should only heal friendly units

~Horse archer - not working. Should be tied to the promotion instead of the unitclass anyways~

~Migration - Civilian units say they have 4 movement, but in practice they only ever get 3. The UI sais 4/2 moves remaining, but the first move costs 2 movement. probably not really a bug; my guess is the game is simply resetting the unit's moves to max (2) after the first move is used.~

**Comment by Infixo** [comment]
If you mean HorseArcherChange.lua then it is simply NOT included in the project and thus doesn't go into the mod.

**Comment by pineappledan** [comment]
Ah. well that should be added then. 

But now that I think about it, I don't think I have removed the Accuracy_I promotion from horse archer yet

**Comment by pineappledan** [comment]
Horse archer is working perfectly now.

Migration has simply been modified in its description to +1 move instead of +2

Hun Bellum Alet still not working
