### ISSUE TITLE
Hippodrome - culture and gold on horse resources

### ISSUE THREAD

**Issue by pineappledan** [adaneslavo/More-Unique-Components-for-VP#121]
Byzantine hippodrome is supposed to give Culture and gold to all horse resources on empire. Currently the wonder only boosts horse resources in the city it is built

**Comment by adaneslavo** [comment]
There is no such function to make this happen.

**Comment by pineappledan** [comment]
hippodrome lua updated. Added event for when capital is conquered

**Comment by adaneslavo** [comment]
On my way.

**Comment by adaneslavo** [comment]
Done.
