### ISSUE TITLE
Exam Hall Change

### ISSUE THREAD

**Issue by pineappledan** [adaneslavo/More-Unique-Components-for-VP#122]
Currently, the Chinese Examination Hall gives Great person points to a randomly selected great person whenever a citizen is born. 

People did not like this system, because it sometimes meant GPPs were awarded for great people that the city was never going to be able to produce. ie. Great artist points in a city with no guild

Instead, it was proposed that GPPs be given to whichever GP meter currently has the most GPPs in the city. (as an absolute value, not as a % of completion).

**Comment by pineappledan** [comment]
Looked at the Exam hall lua.  I'm not sure if I am understanding how it works.

I believe the code picks a random GP to give GPPs to if the number of GPP > 0. So it won't give GPPs to a city for a specialist that city has never worked before. 

Is that correct? If so, then I think we can close this.

**Comment by Infixo** [comment]
No. Currently it gives GPP to any random GP. The Specialists table is used to detect what GPP are actualy valid in the game.
I have updated it to give GPP to the highest "bidder". It will NOT give any points if there are no points produced ever.
