### ISSUE TITLE
Baan Chang too abuse-able

### ISSUE THREAD

**Issue by pineappledan** [adaneslavo/More-Unique-Components-for-VP#123]
Siamese Baan chang gives culture and production boost for every baan chang on empire whenever a City state gifts a unit. 

Currently, this bonus production/culture is all funneled to the capital, so players can predict when CS gifts are coming and rush wonders in the capital with the production boost. 

I propose the bonus culture/production be given to each city with a baan chang instead of all to 1 city. This spreads the bonus out, so it can't be abused to rush certain things.

**Comment by adaneslavo** [comment]
Done. I only need to test it out.
