### ISSUE TITLE
Yamato is standing up

### ISSUE THREAD

**Issue by pineappledan** [adaneslavo/More-Unique-Components-for-VP#124]
Current Yamato is sitting vertically in the water. The axes on the ship's model have been switched. 

Same thing happened with Lanskib model early on in development

**Comment by Infixo** [comment]
It needs updated Animations files.

**Comment by adaneslavo** [comment]
There was some folder with Animations but it contained tons of tons animations. If we want to bring it back it would be wise to pick up only those fragments we are interested in.

**Comment by Infixo** [comment]
Fixed.

![20180314170643_1](https://user-images.githubusercontent.com/25866684/37414791-383718c6-27aa-11e8-973b-21d11c162d39.jpg)
