### ISSUE TITLE
Teutonic Order conversion issue

### ISSUE THREAD

**Issue by pineappledan** [adaneslavo/More-Unique-Components-for-VP#126]
German Teutonic order gives a promotion called "Chapter". On conquest, a unit with the Chapter promotion converts all citizens not following your religion to no religion.

Currently, instead of converting the citizens in conquered cities no religion, citizens are being converted to the German pantheon (but not the full religion)

**Comment by Infixo** [comment]
I don’t think there is a function to convert to a religion. It just adds a religious pressure in the city, like missionaries do.

**Comment by adaneslavo** [comment]
I thing that was what were trying to get: On capture, de-convert all citizens with other faith. Don't we?

**Comment by pineappledan** [comment]
City has 10 citizens:
- 8 Follow Islam (pantheon: God of Wisdom)
- 2 Follow Protestantism (pantheon: Goddess of Love)

Germany conquers city
City now has:
- 2 Follow Protestantism (pantheon: Goddess of Love)
- 8 Follow Goddess of Love pantheon only

**Comment by adaneslavo** [comment]
I imagine that Goddess of Love is Germany's Pantheon and its religion is Prothestantism. Its ok. Code works as intended. We wanted it work that way.

**Comment by adaneslavo** [comment]
We cannot convert to no relligion I suppose. Is that what you would like more?

**Comment by pineappledan** [comment]
If converting to no religion/no pantheon is not possible then I think this is good enough.
