### ISSUE TITLE
Agora change help

### ISSUE THREAD

**Issue by pineappledan** [adaneslavo/More-Unique-Components-for-VP#127]
Need help as to whether this is correct.  the promotion is supposed to change the BaseGold value of the unit with the 'PROXENOS' promotion to 3 (all diplomatic units have a BaseGold value of 1).

GameEvents.CombatEnded.Add(Philhellenism)

function ProxenosGold(iPlayer, iUnit, iUnitType, iX, iY)
	local pPlayer = Players[iPlayer]
	local pUnit = pPlayer:GetUnitByID(iUnit)

	if pUnit:IsHasPromotion(GameInfoTypes.PROMOTION_GREECE_PROXENOS) then
		pUnit:BaseGold == 3
	end
end

GameEvents.UnitCreated.Add(ProxenosGold)

**Comment by Infixo** [comment]
And what is this BaseGold doing or supposed to do?

**Comment by pineappledan** [comment]
On completing a diplomatic mission, influence with the target city state is increased AND gold income of the empire is increased by the value of base gold. 

In effect, every diplomatic unit expended increases gold on empire by 1. This promotion increases that amount to 3.

**Comment by pineappledan** [comment]
Confirmed that Proxenos promotion is being added to units correctly, but the BaseGold value of the unit is not being updated by the lua script.  I don't know the right syntax to have the lua update the value on the unit.

**Comment by pineappledan** [comment]
Okie dokie. So it needs to be added via dummy

**Comment by pineappledan** [comment]
Second attempt: 

function ProxenosGold(iPlayer, iUnit, iUnitType, iX, iY)
	local pPlayer = Players[iPlayer]
	local pUnit = pPlayer:GetUnitByID(iUnit)
	local pGold = GameInfoTypes.BUILDING_DUMMYGOLD

	if pUnit:IsHasPromotion(GameInfoTypes.PROMOTION_GREECE_PROXENOS) then
		local pPlot = Map.GetPlot(pUnit:GetX(), pUnit:GetY())
		local pCiv = pPlot:GetOwner()
		local pCapital = pPlayer:GetCapitalCity()

		
		if pCiv:IsMinorCiv() then 
			pCapital:SetNumRealBuilding(pGold, (pCapital:GetNumRealBuilding(pGold) + 2))
		end
	end
end

GameEvents.UnitPrekill.Add(ProxenosGold)

When unit is killed - checks if unit has proxenos promotion, then checks if unit died in minor civ territory. Then adds 2 gold per turn via dummy buildings in capital

**Comment by pineappledan** [comment]
Tried running a version of this lua with no conditions except for the IsHasPromotion(). Still didn't work. 

Something is wrong with how I have used the lua hook, perhaps?

Can someone help debug? I think this is the only thing holding back a final release at this point

**Comment by Infixo** [comment]
Add to Settings.sql:

`UPDATE CustomModOptions	SET Value = 1 WHERE Name = 'EVENTS_UNIT_PREKILL';`

**Comment by pineappledan** [comment]
That got the trigger working when the diplo unit only checked for the promotion. 

The gold ceased to work when the check for pCiv:IsMinorCiv() was added. 

Also the prekill lua hook fires twice when the unit is expended, so you set twice the amount of gold defined in the lua... super weird it works like that

**Comment by Infixo** [comment]
pPlot:GetOwner() returns an ID, not an object. Use Players[] to get pCiv. Then you can call IsMinorCiv.
Also, I highly recommend checking the lua.log. It would tell you that you are trying to index a number value.

Also, there is another hook active for CombatEnded.

**Comment by pineappledan** [comment]
So like this?
		local pCiv = Players[pPlot:GetOwner()]
		local pPlot = Map.GetPlot(pUnit:GetX(), pUnit:GetY())
		if pCiv:IsMinorCiv() then

**Comment by Infixo** [comment]
Yes, but make sure that GetOwner() returns >= 0. If the plot is unclaimed, it'd return -1, and you'd get an error from Players[-1].

**Comment by pineappledan** [comment]
Does getting an era even matter? If Players[-1] breaks the code then that is okay, since the code isn't supposed to continue in that case anyways

Otherwise, I'll do this then?
local pCiv = Players[math.max(0, pPlot:GetOwner())]

**Comment by Infixo** [comment]
Getting an error is always bad. It’s not up to any discussion.

**Comment by pineappledan** [comment]
Still isn't working.... Latest build:

function ProxenosGold(unitOwnerId, unitId, iUnitType, unitX, unitY, bDelay, eKillingPlayer)
	local pPlayer = Players[unitOwnerId]
	local pUnit = pPlayer:GetUnitByID(unitId)

	if pUnit:IsHasPromotion(GameInfoTypes.PROMOTION_GREECE_PROXENOS) then
		local pPlot = Map.GetPlot(unitX, unitY)
		local pOwner = Players[math.max(0, pPlot:GetOwner())]
       
		if pOwner:IsMinorCiv() then
			local pCapital = pPlayer:GetCapitalCity()
			local pGold = GameInfoTypes.BUILDING_DUMMYGOLD

			pCapital:SetNumRealBuilding(pGold, (pCapital:GetNumRealBuilding(pGold) + 1))
		end
	end
end

GameEvents.UnitPrekill.Add(ProxenosGold)

Works if you take out the 'if pOwner:IsMinorCiv() then' check. Tested with and without the math.max()

Wasn't able to find anything in the lua.log related to the unit.prekill hook
I tried using 'if pPlot:GetOwner() =>22 then' as the check instead of pOwner:IsMinorCiv(), but that didn't work either. (playerIDs between 22 and 62 are for minor civs. 63 is barbarians)

**Comment by pineappledan** [comment]
[Lua.log](https://github.com/adaneslavo/More-Unique-Components-for-VP/files/1874811/Lua.log)
not much really... (6a) Community Balance Overhaul creates a ton of the same error, but not much else

**Comment by Infixo** [comment]
Are you using any other mods or just More Uniques? Because if only More Uniques, then you should fix this first:
[315739.390] Runtime Error: Assets\DLC\Expansion2\UI\InGame\InGame.lua:1262: attempt to index local 'addinFile' (a nil value)
[315739.390] Runtime Error: Error loading Assets\DLC\Expansion2\UI\InGame\InGame.lua.

**Comment by pineappledan** [comment]
Great Prophet Historical Names (BNW or GK)	Version	31
Historical Religions Edit (BNW or GK)	Version	45
(1) Community Patch	Version	88
(2) Community Balance Overhaul	Version	13
(3) City-State Diplomacy Mod for CBP	Version	27
(4) C4DF - CBP	Version	11
(5) More Luxuries - CBO Edition (5-14b)	Version	155
(6a) Community Balance Overhaul - Compatibility Files (EUI)	Version	1
Quick Turns	Version	10
Reforestation	Version	8
More Unique Components for VP	Version	30

**Comment by Infixo** [comment]
Start a new game with just More Uniques and see if the error is still there.

**Comment by pineappledan** [comment]
Those two errors still occured

**Comment by Infixo** [comment]
Klepht.lua is added to the project without the VFS flag set. It should be true.

```
    <Content Include="Greece\Klepth\Klepht.lua">
      <SubType>Lua</SubType>
      <ImportIntoVFS>False</ImportIntoVFS>
    </Content>
```
