### ISSUE TITLE
Fatigue from Khopesh is not coming off of War Elephants.

### ISSUE THREAD

**Issue by ridjack** [adaneslavo/More-Unique-Components-for-VP#128]
As in title, the Fatigue debuff from Egypt's Khopesh appears to be permanent on my War Elephants. I have no other mounted units ATM to test on, but will edit once I do.

EDIT: The problem did not seem to exist with Skirmishers.

**Comment by adaneslavo** [comment]
I checked that and you are right. Seems like War Elephant has no bonus from fortifying and lua code is looking for such thing. @Infixo do you know smth about that? I tested this ability on swordsman and it works. But on war elephant constantly healing from fortification it cannot disappear.

**Comment by adaneslavo** [comment]
This ability cannot work with UNITCOMBAT_MOUNTED or UNITCOMBAT_ARMOR units. It needs to be reworked. @pineappledan ?
