### ISSUE TITLE
Notification text for instant yields from Tophet, Madrasah, etc.

### ISSUE THREAD

**Issue by ziadb** [adaneslavo/More-Unique-Components-for-VP#13]
https://i.imgur.com/XYHBBoR.jpg

As you can see, when buying a unit, a text comes up telling you what exactly happened.

It says: Purchasing a unit has earned you +10 culture from your Tophet in Carthage.

While nice and appropriate, it is not consistent with the way VP handles notifications so the modded buildings will stand out a bit.

I placed a bank in Carthage and bought a warrior to demonstrate how baseline VP handles instant boost yields in cities.

https://i.imgur.com/Xvi3zY2.jpg[/IMG

As you can see, you get two notifications. One is the fleeting upwards floating text through the city showing the exact value. The second is an instant boost dropdown notification that appears on the right which shows the values on mouseover.

If consistency is the goal, then purchasing a unit with Tophet should show the below +10 culture on Standard) floating above the city and a notification dropdown saying:

Bonus Yields in Carthage!
Purchasing a unit or building:
Carthage: +10 culture

**Comment by theazuresoul** [comment]
I can add a notification dropdown in the sidebar, but I cannot incorporate it into the same notification as on the Bank purchase. It would need to be a separate notification, so perfect consistency is not possible.

**Comment by adaneslavo** [comment]
Do what you can. This can be always reworked.

**Comment by adaneslavo** [comment]
I added few floating texts. Please verify if I didn't miss anything. Add also notifications to my buildings (Pitz etc).
