### ISSUE TITLE
Hippodrome - Global WLTKD trigger?

### ISSUE THREAD

**Issue by pineappledan** [adaneslavo/More-Unique-Components-for-VP#130]
The anarchy turns on era are triggered on empire, but the WLTKD turns are only triggered in the capital. Would it not make more sense for the WLTKD turns to trigger on all cities as well?  This looks easily done with a for loop. 

It's been a long time since we had this discussion, and as I recall the reason that was given was that it was not possible to trigger WLTKD in all cities on era switch.  I don't see how that could be the case, because WLTKD is triggered in all cities earlier in the .lua file.

**Comment by pineappledan** [comment]
Seems my memory is shaky, and we always intended it to be the capital only. 

Hinin brought this back up for review in the forum. What do people think?

I don't really have an opinion. The building might be a little too strong if it's empire wide, but I don't really know

**Comment by adaneslavo** [comment]
Changed it. Now need testing.
