### ISSUE TITLE
Mongolia - Minghann promotion

### ISSUE THREAD

**Issue by pineappledan** [adaneslavo/More-Unique-Components-for-VP#131]
The Minghann promotion on The Mongol Black Tug gives +20% CS on pillaged tiles and 5XP on pillage.

The promotion does this by adding/subtracting a massacre promotion via lua. 

The same effect can be done with a promotion with  PillageBonusStrength = 20 and GainsXPFromPillaging = true

This is already done by Denmark's Viking promotion. I think the black tug lua can be scrapped and the minghann promotion can have PillageBonusStrength. The effect should be identical.

Is there anything I am overlooking?

**Comment by adaneslavo** [comment]
I tried that before and it won't work. I asked Infixo about this and it is just blockaded somehow. Sorry. It needs to stay as it is.
