### ISSUE TITLE
All instant yields should scale by gamespeed

### ISSUE THREAD

**Issue by theazuresoul** [adaneslavo/More-Unique-Components-for-VP#14]
The following components should have their yields scaling by gamespeed:

Carthage: Tophet (Culture on unit purchase)
Arabia: Madrasah (Science on unit/GP faith purchase)
America: Ranch (Food and Culture on border growth)
Byzantium: Hippodrome (WLTKD on construction/event)
Babylon: Etemananki (Food and Science on building purchase)
China: Examination Hall (GPP on citizen birth)
Huns: Alti Cur Council ( Science and Gold on tribute)
Maya: Pitz Court (Faith and Science on bak'tun)
Mongolia: Yassa Court (WLTKD on city conquest)
Persia: Pairidaeza (Culture on GA)
Polynesia: Fale Te'le (Culture/Gold/Faith/Faith on building construction)
Siam: Baan Chang (Culture on CS gift)
Sweden: Sauna (Science/Culture on citizen birth)
Zulu: Iziko (Culture on promotion)

**Comment by adaneslavo** [comment]
Siam, Fale, Mongolia, Babylon, Persia - done.
Hyppodrome - half done.

**Comment by adaneslavo** [comment]
Hippodrome done.
