### ISSUE TITLE
Aztec Eagle - Can capture cities by converting garrisons

### ISSUE THREAD

**Issue by pineappledan** [adaneslavo/More-Unique-Components-for-VP#142]
If the last hit that kills a garrisoned unit is made by an eagle, it has a chance to convert that unit into a worker inside the city. Since the worker is occupying the tile of the city, the city is conquered and flips to the attacker as well. So an eagle can conquer a city just by killing the garrison.

**Comment by adaneslavo** [comment]
Awesome! But need to be fixed. I will check that.

**Comment by adaneslavo** [comment]
I cannot reproduce that. I modified lua, but then it turned out that iDefenderDamage was not unit damage, but city damage, so code doeas not progress until city is destroyed. Can you confirm that? @pineappledan ?

**Comment by adaneslavo** [comment]
Fixed, now cannot create worker when capturing the city, even if there is garrisoned unit in it. You can only get workers from loose units around cities.

**Comment by pineappledan** [comment]
I inadvertently broke my SDK, and it would take too long for me to set up this scenario in an actual game :(

**Comment by adaneslavo** [comment]
I made an update. If you will be able to test that, then tell me. It is some time until v32 will be pushed.

**Comment by pineappledan** [comment]
yeah we need to wait for a new VP version anyways

**Comment by adaneslavo** [comment]
Right.
