### ISSUE TITLE
Latifundium's Figs

### ISSUE THREAD

**Issue by Enrico-Swagolo** [adaneslavo/More-Unique-Components-for-VP#143]
Should the Figs only appear adjacently to the Latifundium? If there's no resourceless spots around a Latifundium,  Figs with Plantation won't be created, unlike Indonesian spices (unless there's really no land, they'll be created even under city/at a further spot away). Intentional? I don't think the Latifundium says it only creates them on an adjacent tile.

**Comment by adaneslavo** [comment]
It is coded ad you said. On no city, adjacent, no resource tile. If there's no such tile it won't be created. So the description is unclear? We can fix it.

**Comment by pineappledan** [comment]
The intent was always to have latifundium spawn a fig resource adjacent to itself, but only if there is a tile with nothing on it.  It sounds like it is working as intended

"On construction, immediately spawns an Improved [ICON_RES_FIGS] Figs Resource on an adjacent tile to the Latifundium. The new Figs tile is automatically claimed by Rome."

I think this is clear enough. maybe it should say "available adjacent tile?" I don't think that's necessary though

**Comment by adaneslavo** [comment]
I think 2 things can be added:
- no city tile if this is thing that bothers people,
- it can be placed outside borders and then claims tile. Only claiming tile is not enough for me. It may confuse people.

**Comment by adaneslavo** [comment]
I did a rework of description. It is available on Github. Can you check?

**Comment by pineappledan** [comment]
checked it, made some additional changes
