### ISSUE TITLE
Hacienda text

### ISSUE THREAD

**Issue by Enrico-Swagolo** [adaneslavo/More-Unique-Components-for-VP#150]
+1 [ICON_CULTURE] - City.[NEWLINE][NEWLINE]Additionaly every Mission provides +1 [ICON_PEACE] Faith to the City for every worked Hacienda.[NEWLINE]Only Spain may build it.</Text>
		</Row>

Additionally (one L missing). First every is not needed, and since the bonus applies to the tile, not the city, it appears a bit pointless. You can only have 1 Mission ina city. It's misleading, because someone reading it wrong could think that for every worked Hacienda, every Mission might get +Faith. Why not a short "+1 Faith to each Hacienda worked by the city" on Mission?

**Comment by pineappledan** [comment]
fixed.
