### ISSUE TITLE
Carthage's Suffet description claims it's a Zulu unique unit in the description.

### ISSUE THREAD

**Issue by ridjack** [adaneslavo/More-Unique-Components-for-VP#153]
![image](https://user-images.githubusercontent.com/22875626/42139522-67e8cf34-7d5d-11e8-9a61-0486135d3444.png)

It's correctly assigned and displays properly otherwise; simple text error.

**Comment by pineappledan** [comment]
I think you're using an old version. This was fixed a couple patches ago.
