### ISSUE TITLE
A few oversights regarding faith costs and Civilopedia descriptions

### ISSUE THREAD

**Issue by Phalanx1** [adaneslavo/More-Unique-Components-for-VP#154]
The White Tower's historical info text mentions instead its game info, and the Sauna still is called Bastu in its description, while the Sabum Kibitum and the Great Bombard are still called Khibitum and Great Turkish Bombard, respectively, in their Strategy section of the description.
The Great Galeass and the Turtle Ship are missing faith costs, and the Ballista, the Longbowman and the Hakkapeliitta have different faith costs when compared to the units they replace. The Longbowman also costs more to produce than the Crossbowman (intended?).
EDIT: Disregard the comment on the Longbowman, the production cost is intended.

**Comment by pineappledan** [comment]
fixed all text issues
I changed the name of the Sauna to Bastu so it's more uniform.
Added faith costs to all the units you pointed out. Thanks for finding those.

**Comment by Phalanx1** [comment]
Just wanted to point out another oversight regarding faith costs: some units which come earlier than the units they replace have the same faith cost as the generic units, even the ones who come an era earlier. In VP, the faith cost of units is determined by the tech that unlocks them, with land units from the same era having the same cost and naval units too, each domain with its own default cost. The units in 4UC that should have their faith costs changed because they are available in an earlier era are the Pracinha and the Prau, if I haven't missed anything.

**Comment by pineappledan** [comment]
I made the changes to Prau and Pracinha, and Licorne
I also caught an error with the Fusta's faith cost
All the other ones which come earlier seemed appropriate. Great bombard is consistent with siege tower, in that it is more expensive than anything else in its era.
