### ISSUE TITLE
Kabuki Theatre needs a faith cost

### ISSUE THREAD

**Issue by HungryForFood** [adaneslavo/More-Unique-Components-for-VP#155]
Under the Buildings table, the FaithCost column should be defined for the Kabuki Theatre (to be the same as the Opera House). At the moment, the lack of a faith cost causes Faith of the Masses reformation belief to not work with Kabuki Theatres.

**Comment by Phalanx1** [comment]
I'm not on my PC, so I can't check, but this issue may also be present on the Sambadrome, the Grand École and the Madrasah (which would make those last two not work with Jesuit Education).

**Comment by pineappledan** [comment]
I have added faith costs for Kabuki and Sambadrome for next version.

Madrasah and Grande Ecole have their faith costs already, so no changes required.

Thanks for finding that!
