### ISSUE TITLE
Inconsistency between unit's yields from barbarian kills

### ISSUE THREAD

**Issue by Phalanx1** [adaneslavo/More-Unique-Components-for-VP#156]
I've already explained the issue in a comment [here](https://github.com/adaneslavo/More-Unique-Components-for-VP/commit/e6766cdbe4353bbeb11999cda887284b5a765d72), I'm just submitting this issue to make things more organized.

**Comment by pineappledan** [comment]
This needs to be tested. Both of the promotions are supposed to give double yields if the unit killed was a barbarian. 

So, if a barbarian with 20CS is killed, and UnitPromotions_YieldFromKills and UnitPromotions_YieldFromBarbarianKills are both set at 75, does the game count each separately? Or, does the game look for the highest value, and only count it as one kill? 

Right now, both of the promotions are set at 75 for UnitPromotions_YieldFromKills and 150 for UnitPromotions_YieldFromBarbarianKills. If we want the yields on kills to be doubled for barbarians, do we set UnitPromotions_YieldFromBarbarianKills to 75 (75+75 = 150), or do we set UnitPromotions_YieldFromBarbarianKills to 150 (150 + ~~75~~0 = 150 )?

**Comment by Phalanx1** [comment]
What you said is incorrect, unless I misread the code. For the Indian UU, both YieldsFromKills and YieldsFromBarbarianKills are set at 75, while on the Polish one YieldsFromKills is set at 150 and YieldsFromBarbarianKills is set at 300. As for which one is correct, I have no idea.

**Comment by pineappledan** [comment]
I played a game with India where yields from kills were set to 75, and barbarian kills were set to 150. 
Bogurodzica is set at 150 and 300, yes. I misspoke, but the issue remains: If we want 2x yields from barbarians, do we get X from a kill + Y from a BarbKill, or does the game just give yields for whichever one is higher?

**Comment by Phalanx1** [comment]
I can't test right now, if I have time I'll run a quick India game and tell you the result.

**Comment by pineappledan** [comment]
Thanks for checking.

You'll have to look at your total culture in your policy progress meter. 

If the culture is being double-counted, it is not showing up in the floating text on kills. I can tell you that much at least.

**Comment by pineappledan** [comment]
I tested it. 
yieldFromKills=75
YieldFromBarbarianKills = 150
killed a barbarian (7 CS). The resulting culture was 15 (7*2.25, rounding down)

I deduce from this that the proper setting for this is for barb kills to be 75, and yield on kills to be 75. 

I will now consider the matter closed
