### ISSUE TITLE
Bought/produced Sea Beggars don't get Prize Ships, only upgraded ones do

### ISSUE THREAD

**Issue by Enrico-Swagolo** [adaneslavo/More-Unique-Components-for-VP#158]
Basically Title. It wasn't happening on vanilla 15/07 version with the Dutch (bought and produced Baggers all had the promo), so I think some code about the promotion is broken here because it's the only thing that changed and the only other mod I use (excluding VP promo icons and other such small stuff that affects nothing in this regard).

Also, you can get Prize Ships with a level up. I think lvl2 or lvl1 melee ship city attack tier allows it to be taken. At least on Beggars, that is, they're allowed to get what they normally get for free. Weird. I can buy a caraval and check if it does too

**Comment by Enrico-Swagolo** [comment]
Checked, got Caravel, Skull line didn't allow them to get Prize Ships, so only Sea Beggars - bought, produced, not upgraded - have the access, but they don't get it for free

**Comment by Enrico-Swagolo** [comment]
Tersane IS guilty! I removed the line about Prize Ships from Tersane.lua, and reloading the save and buying Sea Beggar gave him his well-deserved Prize Ships.

**Comment by pineappledan** [comment]
Resolved! Inserted a check that aborts the Tersane's lua if the unit built was a sea beggar
