### ISSUE TITLE
Japanese Yamato "Kantai Kessen" promotion not giving Great Admiral points

### ISSUE THREAD

**Issue by Laz0rG** [adaneslavo/More-Unique-Components-for-VP#159]
during a victory the popup over the defeated unit's tile saying how many GA points I would have gotten from the promotion appears, but the actual GA points don't add to the total count in the GA counter during or after the turn. This might be the case for the Armada unit too, didn't try that though.

**Comment by pineappledan** [comment]
This is a problem which will require a fix to VP's DLL... Otherwise we could leave it as is and create a new lua trigger which adds the GA points that way. A DLL fix would be more elegant, however. 

Might have to submit a feature request for CBP. Can you post a picture, Laz0r?

**Comment by pineappledan** [comment]
I created an issue on VP, and it has been marked as resolved for the next version
