### ISSUE TITLE
schutzenstand description

### ISSUE THREAD

**Issue by Enrico-Swagolo** [adaneslavo/More-Unique-Components-for-VP#165]
It says it increases supply by 15% in the upper part, but the lower part only mentions 10%.

In addition, it says it gives "30% Production and 15XP towards gunpowder units". Sounds a bit off for me. A similar thing is given by Ducal Stable whose description imho sounds better, I'd replace "towards" with "for"

**Comment by pineappledan** [comment]
I have made the change. Thank you for your continued work.
