### ISSUE TITLE
Sambadrome: +25% Golden Age points during Golden Ages

### ISSUE THREAD

**Issue by Phalanx1** [adaneslavo/More-Unique-Components-for-VP#166]
What's the point of this? I thought you could only earn Golden Age points when not in one. Am I missing something?

**Comment by adaneslavo** [comment]
Good point. I know theres small modmod making it possible. Do you have some screens confirming it is not working? Can you check that?

**Comment by Phalanx1** [comment]
I actually don't have an ongoing game, so I can't check, but I do know that in the base game you can't earn GA points while in one. The thing I'm not sure of is whether VP changes that or not.

**Comment by pineappledan** [comment]
I could almost swear that I have triggered a natural golden age while already in a golden age while playing as Persia. 
I could be mistaken though.

**Comment by adaneslavo** [comment]
http://www.picknmixmods.com/mods/CivV/Global/GA%20Happiness.html
This is the mod I was thinking about. It is for base game. Maybe VP don't need it. If you could check then it would be helpful. We are working on big update, so if it doesn't work, then we would need to rethink that idea form scratch.

**Comment by Phalanx1** [comment]
That mod is not listed as an integrated mod on Civfanatics, but I'll check it out anyway. I won't have time to do it until Sunday, though. If any of you have an ongoing game without the mod, test it for me, please. It would save quite some time.

**Comment by adaneslavo** [comment]
Easy we do not rush this update. I wait for some more balance suggestions concerning other civs. If you check this this week it will be ok,

**Comment by adaneslavo** [comment]
I checked this last afternoon and Ga points are amassed during golden ages. So, no additional mod is needed and Sambadrome bonus works well.
