### ISSUE TITLE
Goedendag description

### ISSUE THREAD

**Issue by Enrico-Swagolo** [adaneslavo/More-Unique-Components-for-VP#171]
The way it's stated, it sounds like the unit comes in groups, so making one creates a few of them. it says I suggest something like
"Cheap, versatile Pikeman replacement that supports other units." or
 "cheap, versatile unit capable of strengthening nearby allies",

**Comment by adaneslavo** [comment]
I did: "A cheap, versatile offensive unit with supporting abilities."
