### ISSUE TITLE
Homestead not claiming Horse, Sheep, Cattle and Bison on construction.

### ISSUE THREAD

**Issue by Serind92** [adaneslavo/More-Unique-Components-for-VP#173]
title ^^
Not sure about neutral territory but it definitely dosen't work on titles (in the workable area ofc) already owned by other civilizations.

**Comment by adaneslavo** [comment]
It should claim your or neutral tiles in 3tile range from city. I tested it with few guys. Are you sure it do no work?

**Comment by Serind92** [comment]
NVM then i thought it should also work for titles owned by other civilizations, my bad.

**Comment by adaneslavo** [comment]
We had such idea but thought it would be too op.
