### ISSUE TITLE
Missing uniques, EUI bugs

### ISSUE THREAD

**Issue by Zakuzelo** [adaneslavo/More-Unique-Components-for-VP#174]
Having some serious issues with version 37.

-Several UUs arn't showing up. Assyria's unique walls, Poland's armory/castle, India's castle, and Austria's arsenal all don't exist.
-More frustratingly, the mod is now breaking EUI. I reinstalled VP altogether to try and fix the above, and since then leader screens are busted. No buttons, blank boxes with a Washington icon in the leader HUD, that sort of thing.

Had 36 still laying around so tried that too, no change.

**Comment by adaneslavo** [comment]
What version do you use? We probably had such problem before for one of users and updating VP helped. Please make sure to post log files (database.log and lua.log). Google will help you in enabling logs. Without that I cannot do much. Me and few guys use v37.2 (soon v37.3) with or without VPEE and it works well.

**Comment by adaneslavo** [comment]
I found it on forum thread:
> Hello. Can you help me? Some civs has no 4th UC: Assyria, Poland and few others. I checked Assyria and it does not have walls, even normal one. Only mods that used were Vox Populi with EUI and this mod. Also I tried to clean cache folder, did not help. Did I miss something? Any files are needed to run this mod? Thanks in advance!

and his response after my help:
>Oh, mine is 8-7-4. I downloaded it from Google Drive, alternate location. Is it old version there? Mega.nz is banned where I live. Yep, I can see now. Open mega using VPN. I was playing with old version all the way... Sorry, for bothering :)

**Comment by Zakuzelo** [comment]
Logs w/ Vox components:
[Database.log](https://github.com/adaneslavo/More-Unique-Components-for-VP/files/2389987/Database.log)
[Lua.log](https://github.com/adaneslavo/More-Unique-Components-for-VP/files/2389988/Lua.log)

And with MUCfVP added in:
[Database.log](https://github.com/adaneslavo/More-Unique-Components-for-VP/files/2390043/Database.log)
[Lua.log](https://github.com/adaneslavo/More-Unique-Components-for-VP/files/2390044/Lua.log)

I'm not sure where to see what version of VP I've got, every component has it's own number and all, but I reinstalled it just yesterday. I _should_ have the latest version, unless the auto-installer is messed up.

**Comment by adaneslavo** [comment]
Just go to the forum of civfanatics-community patch. Download .exe file from latest beta realease thread from mega.nz link posted by Gazebo and it has always number assigned. I currently use Vox Populi 9-15 (earlier 9-6-2). You probably have version before 8-6.

**Comment by Zakuzelo** [comment]
I thought I was. The version in the sticky isn't the latest one? Weird. 
Well, working fine now. Problem solved, probably more than just that one too. Thanks.
