### ISSUE TITLE
Aztecs - Huey Teocalli (Bug)

### ISSUE THREAD

**Issue by Serind92** [adaneslavo/More-Unique-Components-for-VP#179]
"receive permanent +3 Faith and +3 Food, and +3 XP to units trained in the City (stacks 10 times) Whenever a Golden Age Start" is completely buged. Dosen't give food or exp, but instead gives crazy amount of "faith from population" im at +126 in the medieval era after 4 (maybe 5 triggers).

**Comment by pineappledan** [comment]
Aztecs hasn't been touched in a long time, and we haven't had this issue crop up before. Can you please post logs, and modlist?  If you can, a picture of the cityView with Hury Teocalli in it would also be helpful

**Comment by Serind92** [comment]
![obraz](https://user-images.githubusercontent.com/37441111/47603657-8b2a0c80-d9ef-11e8-8a65-e54ccb3a67dc.png)

Thats the most recent save i have from that game, but after getting 1 more golden era(it was from artist), religion from population jumps to ~120.

![civ5screen0002](https://user-images.githubusercontent.com/37441111/47603677-caf0f400-d9ef-11e8-8288-347b856d8053.jpg)

**Comment by pineappledan** [comment]
Okay, so you are getting 88 faith from population. Exactly 4 per population (88/22 = 22)

Huey Teocalli definitely isn't at fault, because the bonus faith it gives is through dummy buildings, and the amount of faith from buildings isn't terribly high (26 total).

**Comment by Serind92** [comment]
WC reformation, Tree growth, Trade ui and both promotion mods were added recently, so it's a possibility. events and decisions i've been using as long as MUC and i remember Huey working before.

**Comment by Serind92** [comment]
You were right with population  I loaded game earlier before signing winning peace treaty and took 2 screenshots.  (still don't know why im getting all that faith from population tho and why it's x2 the population less compared to different save from 2 turns earlier). 
![civ5screen0003-1](https://user-images.githubusercontent.com/37441111/47609265-b63a4d80-da3b-11e8-9c18-17f827ca05ff.jpg)
![civ5screen0004](https://user-images.githubusercontent.com/37441111/47609266-b76b7a80-da3b-11e8-848b-01c9d77661ba.jpg)

**Comment by pineappledan** [comment]
I guess I will close this ticket then.

As a general note, I wouldn't advise using more than 1-2 of these bigger mods at a time. Yield inflation is a very real problem in these cases, even if no bugs or mod conflicts arise.

**Comment by Serind92** [comment]
I tried again using 
![civ5screen0005](https://user-images.githubusercontent.com/37441111/47745398-dbb99800-dc83-11e8-8a82-8071fa7c17f1.jpg)

Gives 0 exp to units (both on trained and bought units)
Gives 2 Food
![civ5screen0002](https://user-images.githubusercontent.com/37441111/47745741-a5c8e380-dc84-11e8-8ef3-834a8919d272.jpg)
![civ5screen0001](https://user-images.githubusercontent.com/37441111/47745785-c2651b80-dc84-11e8-826a-a63b1a3af40d.jpg)
Faith seems fine.
