### ISSUE TITLE
Yield disparity between stone and hills for monolitic church

### ISSUE THREAD

**Issue by Rafs041** [adaneslavo/More-Unique-Components-for-VP#187]
When building monolitic church on hills, some of the yields are not present (seem to be the ones related to religion from what I can see).
Playing on a comunitas map if that helps, aside from vp and the 3&4UC mod I also used infoaddict.
![20190506124138_1](https://user-images.githubusercontent.com/19327087/57220668-85476080-6ffc-11e9-9839-1f6fb6a7e999.jpg)
Any other file that I need to upload?

**Comment by pineappledan** [comment]
Tested it and made a new version. It's working now
