### ISSUE TITLE
Austrian Grenzer losing combat strength from diplomatic marriage

### ISSUE THREAD

**Issue by SaltyIceCream** [adaneslavo/More-Unique-Components-for-VP#191]
CS went down from 35 to 34 when I promoted one unit.

**Comment by pineappledan** [comment]
The CS changes whenever the unit is promoted instead of checking each turn
Base CS is 33, so it looks like you're still getting +1 from a diplomatic marriage. Is it possible that one of your married CS was conquered or otherwise lost?

**Comment by SaltyIceCream** [comment]
Hey, thanks for answering! Afaik, base CS from Austrian Grenzer is 35 and each individuell city state marriage should increase it by 1. However when I trained one unit AFTER I married my first city state, the CS went down from 35 to 34. It was not only a visual bug because I tested it against another unit in combat and it now was definetely weaker than before.

**Comment by pineappledan** [comment]
It's set to 33 in the lua. I will update for next version
