### ISSUE TITLE
v73 issues

### ISSUE THREAD

**Issue by bazaarjack** [adaneslavo/More-Unique-Components-for-VP#192]
- Klepht (Greece) : missing unitclass type commando
- Tersane (Ottomans) : column not defined on table improvement (nofollowup) 

@pineappledan 
I suspect that v73 requires changes that are in the August beta (tersane) or in your Pdan's tweaks (klepht) - not sure though.

**Comment by pineappledan** [comment]
The Klepht replaces a new Commando unit. The Zeppelin is gone from the scout line and has been replaced with the Commando. 

You'll have to upgrade to a newer version.

The Tersane thing is also new code that you might not have if you havent updated. It's the code that lets melee units retreat back to the tile if they kill a unit. This used to be a hardcoded ability to forts and citadels.
