### ISSUE TITLE
Sachem's Council not granting Reciprocity to Great Diplomats.

### ISSUE THREAD

**Issue by thecanidcoder** [adaneslavo/More-Unique-Components-for-VP#193]
v74

![image](https://user-images.githubusercontent.com/22875626/143963595-a502bff2-add9-4866-860d-0928298a78b0.png)

![image](https://user-images.githubusercontent.com/22875626/143963666-96de8805-fed4-4f62-a5d0-76a194ea5bcf.png)

**Comment by pineappledan** [comment]
tested this on local install and I got the Reciprocity promo as intended

**Comment by pineappledan** [comment]
Sachems council no longer exists.
