### ISSUE TITLE
Nilometer spawns Flax to foreign City - v75

### ISSUE THREAD

**Issue by bentakacs** [adaneslavo/More-Unique-Components-for-VP#194]
Henlo PD!

I wouldn't necessarily call this as a bug, just thought I'd mention in case you're unaware of it and easy to "fix".
Thank you for the continuous updates on 4 UC !

![ask PD](https://user-images.githubusercontent.com/22188835/152778159-dc13ac01-d565-46dc-ada7-e7a3205eaec4.png)

**Comment by pineappledan** [comment]
Nilometer spawns flax within 3 tiles of the source city, and will prioritize rivers, but does not check for Egyptian-owned tiles. This is intended
