### ISSUE TITLE
Celtic Scythed Chariot model missing

### ISSUE THREAD

**Issue by pallasinine** [adaneslavo/More-Unique-Components-for-VP#197]
![image](https://user-images.githubusercontent.com/104652858/166061624-c21bba3b-c352-42b6-99a2-a7e71c2a070d.png)

The Scythed Chariot appears to have no model in v76 with the most recent version of VP (image attached.)

On initial production, it caused a series of blue and brown planes to take up most of the screen when it was present on the right side of the screen, but I have not been able to replicate that issue since saving and reloading.

**Comment by pineappledan** [comment]
Changes were reverted
