### ISSUE TITLE
Latfidium does not create figs plantation on completion

### ISSUE THREAD

**Issue by jayeye2011** [adaneslavo/More-Unique-Components-for-VP#199]
Current v86 (fifth iteration), Rome latfidium improvement upon completion is supposed to generate a fig plantation tile adjacent to the latfidium improvement according to the tool tip, but it does not. See screenshots below

![t34](https://github.com/adaneslavo/More-Unique-Components-for-VP/assets/69315126/8edcee3e-879e-4fcb-91fc-380e99ce2fcb)

![t35](https://github.com/adaneslavo/More-Unique-Components-for-VP/assets/69315126/4e290e11-8658-418c-bf5a-fe8510a5550d)

**Comment by adaneslavo** [comment]
@pineappledan?

**Comment by jayeye2011** [comment]
I believe the issue is in Latifundium.lua at line 50:
local iChosenPlot = math.random(#tPossibleSpots - 1, "") + 1
Comparing it to a version where figs were created correctly line 50 was:
local iChosenPlot = Game.Rand(#tPossibleSpots - 1, "") + 1

**Comment by jayeye2011** [comment]
If math.random is the problem, then you might want to check where you used it in other lua files
Search "math.random" (6 hits in 4 files of 65 searched)
  C:\Users\john_i\Documents\My Games\Sid Meier's Civilization 5\MODS\(over) More Unique Components for VP (v 86.5) vp3.7.7\Shoshone\BuffaloPound\BuffaloPound.lua (2 hits)
	Line  61: 		pChosenPlot = pSpotsTable[ math.random(#pSpotsTable) ]
	Line 131: 			pChosenPlot = pSpotsTable[ math.random(#pSpotsTable) ]
  C:\Users\john_i\Documents\My Games\Sid Meier's Civilization 5\MODS\(over) More Unique Components for VP (v 86.5) vp3.7.7\Portugal\Cacadores\Cacadores.lua (1 hit)
	Line 57: 	pUnit:SetHasPromotion(tAvailablePromotions[ math.random(1, #tAvailablePromotions) ], true)
  C:\Users\john_i\Documents\My Games\Sid Meier's Civilization 5\MODS\(over) More Unique Components for VP (v 86.5) vp3.7.7\Egypt\Nilometer\Nilometer.lua (2 hits)
	Line  77: 					local pChosenPlot = table.remove(tPossibleSpots, math.random(#tPossibleSpots)) -- don't use again
	Line 187: 			local pChosenPlot = table.remove(tPossibleSpots, math.random(#tPossibleSpots)) -- don't use again
  C:\Users\john_i\Documents\My Games\Sid Meier's Civilization 5\MODS\(over) More Unique Components for VP (v 86.5) vp3.7.7\Aztecs\Eagle\Eagle.lua (1 hit)
	Line 16: 		if math.random(4, "Eagle capture roll") == 1 then

**Comment by pineappledan** [comment]
This math.random switch thing has been the bane of my existence. I will have this resolved with the next version.
