### ISSUE TITLE
Different era scaling between bg and adan part

### ISSUE THREAD

**Issue by adaneslavo** [adaneslavo/More-Unique-Components-for-VP#26]
We need to decide on one pattern.

**Comment by adaneslavo** [comment]
I started changing that. Verify if all is changed.

**Comment by adaneslavo** [comment]
Check if there's some ability that needs adding such scaler. I added it to few of mine.

**Comment by adaneslavo** [comment]
I found that:
```Scaling is :
Ancient : x1
Classical : x1
Medieval : x2
Rennaissance : x3
Industrial : x4
Modern : x5
Atomic : x6
Information : x7 ```so you were partially right. The only thing that needs to be changed now is setting x1 for ancient.

**Comment by theazuresoul** [comment]
I'm quite sure that that is the formula I was using. max(1, era), which sets x1 for ancient.

**Comment by adaneslavo** [comment]
Yeah, but I reverted it yesterday to version from my part becaue values were to high and scaled wrong. I need to revert them now to your code and adjust values.
