### ISSUE TITLE
Iron chariot lua changes.

### ISSUE THREAD

**Issue by adaneslavo** [adaneslavo/More-Unique-Components-for-VP#28]
Remove player do turn event. Verify if on create or on train functions are needed. Probably yes.

**Comment by adaneslavo** [comment]
Ok, I checked why for me onMove trigger didn't work. I can tell you that is because I need to check if adjacent unit has some promotion. When you create one and take scan for adjacent units it treats newly created one like it wouldn't have any promotion. You for Iron Chariot check only for some unit and don't bother with promotions.

**Comment by pineappledan** [comment]
So this is resolved then?

**Comment by adaneslavo** [comment]
No. Plot iterator can be in any file using it or in plotiterator itself. I resolved 3 lua bugs in your files when there was using pAttackingUnit:function and there was no unit.

**Comment by adaneslavo** [comment]
Delete playerdoturn event and check if it is fine. I think it is useless now, but had no time to chekc that.

**Comment by adaneslavo** [comment]
I reworked this code. I found situation where Iron Chariot didn't get bonus from Fury of Nergal. F.e. 3 barbs and then between them Iron Chariot is Created. No effect on him.
