### ISSUE TITLE
Restrict Landwehrs Yorkshire March. Era scaling issue.

### ISSUE THREAD

**Issue by adaneslavo** [adaneslavo/More-Unique-Components-for-VP#33]
Add restrictions:

- garrison

- fort

- citadel

- ???

**Comment by theazuresoul** [comment]
Is this restriction necessary? It's a small amount of culture, far less than you would get from a building of equivalent cost, and not affected by percent modifiers. Restricting it would make it more difficult for the AI to use. I don't care either way, but I don't see this as necessary.

**Comment by adaneslavo** [comment]
We will see. I added scaling with era and game speed. We can always rework it.

**Comment by theazuresoul** [comment]
I don't see era and game speed as necessary either. This is essentially a per turn yield, and those don't scale with game speed. And most constant yields don't scale with era either.

**Comment by pineappledan** [comment]
Even with the current implementation, the scaling would be hardly noticeable. I wonder if that isn't simply unnecessary burden for the computer?

I don't think unit yields should scale if they are static yields, Units obsolete, unlike buildings, so they aren't purpose-built to be relevant in later eras

**Comment by pineappledan** [comment]
reopened because there seems to still be some discussion about what this promotion should be. 

Okay, so do you guys want this to be a considerable source of culture, something that makes a material contribution to the Austrian economy?  I had always envisioned this promotion as an added flavor, but not necessarily a core competency of the unit.

**Comment by adaneslavo** [comment]
Units get obsolete, but promotions stay after upgrade in most cases. And if it scale for landwehr on fast from 1c on industrial to 2 on information it is not such big deal. How it is implemented in VP? I made such scaling for all buildings and units, code like BG, but sometimes different values (depending on what era building or unit is from).

**Comment by adaneslavo** [comment]
I'm in favor of restricting it somehow. But I'm not tied to forts, citadels and garrison so much.

**Comment by Infixo** [comment]
What is this Landwehr supposed to do? I read texts and it's totally unclear - it's nicely written but doesn't say anything game related.

**Comment by adaneslavo** [comment]
Landwehr has 2 basic bonuses from new promotions:
- Yorkshire gives culture if unit is in **your** territory and is:

1. standing on fort or citadel
2. is garrisoned in the city
- imperial vigilance adds bonus CS to landwehr if it is in CS territory.

**Comment by pineappledan** [comment]
To put it into perspective. I think that 2 culture per landwehr anywhere in friendly could realistically mean your army is outputting as much culture as a 2nd tier city. Given the AI's love of unit spam, its higher unit cap, and its general disregard for unit cap, It seems like making the culture's only limitation that you are in your own territory feels like handing the AI a loaded gun. 

I thought the %CS boost was also in your own territory, not just CS territory?

**Comment by adaneslavo** [comment]
Code said differently so I adjusted descriptions.

**Comment by Infixo** [comment]
Re: Vigilance. Don't you get 3 events now when a unit is trained?

**Comment by Infixo** [comment]
Also, since you've got promotion with FriendlyLandsModifier=25 then why do you need to switch it off and on? You grant promotion (from Unit_FreePromotions) and engine does the rest assuming that your definition of "friendly" land is the same as in the game.

**Comment by adaneslavo** [comment]
Ok? Seems reasoable to get rid off that one promotion.
We have a lot more such dummy promotions. Can you check them if they are needed or maybe substituted somehow? Yellow Brow, Black Tug etc.

Problem with this type of events is:
- on move doesn;t work quite well with creation and building units because you can't see in the same turn what promotions unit has (it returns nil for that one turn). Maybe some dll tweak? Then oncreate and onbuild wouldn't be necessary.
- on create is triggered on gifts and pawns units but not training in the city so they are not overlapping each other.

**Comment by Infixo** [comment]
So... this Friendly field doesn’t work when CS is an ally? Weird.

**Comment by adaneslavo** [comment]
Friendly is probably tied to both: yours and CS territory. I don't know if it is treating about ally and friend or only friend or only ally. Only third option would be satisfying.

**Comment by pineappledan** [comment]
Okay so it IS active in owned territory (base promotion), and also CS territory (dummy promotion).  

I think with the restriction of garrisons, forts and citadels the culture per turn could be increased to 3. I wouldn't go beyond that though. While I think it's a nice bonus, I don't think this unit should be rewarding you for spamming them in peace time to mill culture. Get enough for your cities and fortifications and that should be fine

**Comment by adaneslavo** [comment]
I reverted base value to 0 so it is now only allied. What was the initial plan? I thouht it was only CS.

**Comment by pineappledan** [comment]
From Blue Ghost's description on forum page 1:
"Imperial Vigilance (+25% CP in friendly territory)"

From 4UC spreadsheet:
Imperial Vigilance (+25% CS in owned territory and in allied city-state territory)

**Comment by adaneslavo** [comment]
So friendly means your territory only?

**Comment by adaneslavo** [comment]
Ok, then I will change it back. What about that era scaling issue?

**Comment by pineappledan** [comment]
it's 0.2 culture. You need 5 landwehr to get 1 additional culture per era. frankly it's so immaterial it won't be noticed even it is there.

**Comment by Infixo** [comment]
So, you need an Ally CS but not Friend? Well, you need really precise descriptions for this sort of „little differences” or people will get confused :)

**Comment by pineappledan** [comment]
I don't think static yields on units should scale, because supply cap increases -> more unit -> more yields. ie. scaling. 

Where this debate will really matter is that Tarkhan proposal, with it yielding 10 culture/20 Gold every turn in a razing city

**Comment by pineappledan** [comment]
Ally, friend. I don't think It matters which one. If You're playing austria you're likely allied with everyone anyways.

**Comment by adaneslavo** [comment]
I made it to be: your + friendly CS + ally CS for sake of simplicity.

@Infixo What is the situation with static yields scaleing on unit in VP?

**Comment by theazuresoul** [comment]
I don't think there are any units in VP with static yields. If there were, I don't think they would scale. Static yields on buildings don't scale.

**Comment by Infixo** [comment]
What do you mean "static yields", like yields for kills? What unit in VP uses those, I need an example, so I can tell you exactly how it is processed.
OnMove - I was tracking few days ago a situation with barb camp capture, so the barb unit would join the capturer. The code for unit creation and movement is so complex that I won't dare touch it. Sorry.

**Comment by adaneslavo** [comment]
Ok, so we must stay with what we have now: 3 functions, each taking its own part and sometimes overlapping themselves, but together covering every situation met on battlefield.

On kill is used for example by Pictish Warrior. It scales with combat strength of defeated unit so not direcly but the other way scales with era (later era, stronger opponents). We added for example Landwehrs culture per turn (3c). Should scale somehow with progressing eras? I made qizilbash exaple in this thread earlier. You can also look there.

**Comment by pineappledan** [comment]
Static yields defined as yields per turn, independent of any condition.  In our mod's case we have 3 units that have yield per turn "flows"
- Landwehr (industrial): 2 culture per turn in friendly (or 2 culture in garrison/fort/citadel)
-Qizilbash (renaissance): 2 GAP, 2 Gold and 1 Faith per turn in enemy territory
- Tarkhan (ancient): 10 culture and 20 gold per turn in a city that is being razed

I agree. I can see an exception being made for Tarkhan, who has a very specific yields per turn condition (being stationed in a razing city), but that's it.  If you want more unit yields from static flows from units, then the obvious fix is to build more units.

**Comment by adaneslavo** [comment]
I added era scaling also to Holkan, Klepht and Dhanurgraha. Rework them all if think they are not necessary.

**Comment by pineappledan** [comment]
Does science/culture from Dojo's yields on levels scale for Japan?

**Comment by adaneslavo** [comment]
I barely played Japan so I cannot tell that.

**Comment by pineappledan** [comment]
As per ElliotS, they do not. I think that is as strong an argument against making the flows scaling as we are going to get

**Comment by Infixo** [comment]
Pictish Warrior doesn't scale with era. It simply uses opponent's CS for calculations. "Scales with Era" is e.g. when you get 10 in Classical, 20 in Medieval, 30 in Renaissance, etc. It seems that there are no units that works like this in VP.
Dojo scales culture, etc. based on unit level, nothing to do with era. I think only Policies and Beliefs have effects that scale with Era.

**Comment by adaneslavo** [comment]
Ok, I will revert era scaling from units.
