### ISSUE TITLE
Lua for Japan

### ISSUE THREAD

**Issue by theazuresoul** [adaneslavo/More-Unique-Components-for-VP#47]
Yamato - need lua to trigger GA points whenever a yamato is constructed, and GAP/culture yields for whoever kills a Yamato.

**Comment by pineappledan** [comment]
I have made an attempt at lua for Japan. Someone please come in and check if this is alright

**Comment by Infixo** [comment]
You can't just use UNIT_YAMATO directly, you need to use GameInfoTypes.UNIT_YAMATO. All types are kept in GameInfoTypes.

**Comment by pineappledan** [comment]
done. if that is the only issue then this lua is closed and Japan is ready

**Comment by adaneslavo** [comment]
So extract it from temp folder into main one and add all files to project so we could test it properly. For now it is invisible.
