### ISSUE TITLE
Lua for Korea

### ISSUE THREAD

**Issue by theazuresoul** [adaneslavo/More-Unique-Components-for-VP#48]
~~Chaebol - need lua to give Chaebol building Gold and % GPPs for every international trade route on empire~~

**Comment by Infixo** [comment]
0. Create a dummy with effects for 1 TR
1. numTR = pPlayer:GetNumInternationalTradeRoutes()
2. Find city with Chaebol
3. pCity:SetNumRealBuilding(dummy,numTR)
This way yields will be shown in tooltips.

**Comment by adaneslavo** [comment]
Similar way like Waag has GPP and Defense.

**Comment by Hokath** [comment]
Submitted pull requests, please give it a quick once-over
