### ISSUE TITLE
Lua for Zulu

### ISSUE THREAD

**Issue by theazuresoul** [adaneslavo/More-Unique-Components-for-VP#49]
InDuna - need lua for giving XP to stacked and adjacent units when an InDuna is expended (ie. on citadel construction)
~~Iziko - need lua for culture when a unit levels up on empire~~

**Comment by Hokath** [comment]
The AI isn't going to be able to use InDuna, is it? Perhaps it should give empire-wide xp like those city state quests instead

**Comment by Infixo** [comment]
Certainly not "on purpose". Only by chance.

**Comment by pineappledan** [comment]
It's not like the AI doesn't know to stack units on great generals. 

Looking at the Dojo code, it looks like the Iziko code can be implemented in sql

**Comment by Hokath** [comment]
It's not that they wont stack, its if they stack while building a citadel. Usually I see them send generals to the front to citadel-bomb tiles during peacetime.

I will make the Iziko change.

**Comment by pineappledan** [comment]
I'm guessing the easiest way to do this would be to trigger on creation of citadel improvement
If Zulu, on citadel creation, 60XP on citadel plot, 15XP on plot adjacent to citadel

**Comment by Hokath** [comment]
I would suggest a rethink. Something that boosts the unit with which the general is stacked, perhaps.

**Comment by pineappledan** [comment]
New InDuna lua proposal; 2 effects:
- stacked unit gains 5XP on attack
- on expending InDuna, 30XP for stacked unit and 30 damage immediately on all adjacent enemy units (an immediate fortress action)
