### ISSUE TITLE
Lua for Inca

### ISSUE THREAD

**Issue by theazuresoul** [adaneslavo/More-Unique-Components-for-VP#50]
Chasqui - need lua for 15HP heal every turn on unit when inside owned territory (like a march promotion, but only in your own land)
Tambo/Coca - need lua to give/remove unique Coca monopoly promotion to all military units when empire gets/loses monopoly on Coca. Need the same thing for all civilian units (military and civilian units get 2 different promotions from coca monopoly)

**Comment by Infixo** [comment]
There is a fields in UnitPromotions that can be used: FriendlyHealChange

There are 5 promotions that use it:
```
PROMOTION_FASTER_HEAL
PROMOTION_MEDIC_GENERAL
PROMOTION_INVULNERABIILITY
PROMOTION_GUERILLA_FIGHTER
PROMOTION_EVERLASTING_YOUTH
```

**Comment by pineappledan** [comment]
Isn't that only on fortifying though? The idea is the promotion needs to heal every turn, regardless of unit action

**Comment by pineappledan** [comment]
Created a chasqui lua. please check my work

**Comment by pineappledan** [comment]
Tambo lua

I don't know the arguments for HasGlobalMonopoly()

**Comment by pineappledan** [comment]
Okay, so that is as written currently. Check can someone check if the rest looks okay?

**Comment by Infixo** [comment]
1. Chasqui - you don't need any Lua for that. There's FriendlyHealChange that heals in friendly territory.
2. Tambo - I will work on it.

**Comment by pineappledan** [comment]
I'm not sure if you are understanding me. FriendlyHealChange augments healing when in friendly territory. It does not trigger healing in and of itself. in order to have healing take place in combination with another action (ie moving or attacking) then you need AlwaysHeal=1.

**Comment by Infixo** [comment]
So basically you want to give x hp every turn the unit is within friendly territory. If so, there's no need to flip-flop promotions, it only takes time. PlayerDoTurn() iterate through units, if they have the required promotion and are within friendly territory then grant HP.

**Comment by pineappledan** [comment]
That sounds about as intensive as the current way it is programmed. I'm not sure which would be better

**Comment by adaneslavo** [comment]
Fixed.

**Comment by Infixo** [comment]
Fixed again :)
