### ISSUE TITLE
Lua for Songhai

### ISSUE THREAD

**Issue by theazuresoul** [adaneslavo/More-Unique-Components-for-VP#51]
~~Sofa - need lua for new promotion. essentially a copy of the GG 15% RCS/CS boost if within 2 tiles, but ONLY applies to mounted units. So if mounted unit is in 2 range of a sofa it gets boost~~
~~Qadi - need lua to convert 10% production to culture in city. The Indian Qila does the exact same thing, but with food, you can lift code from there.~~
Qadi - need lua for 'jizya' effect; 1 Gold for every citizen not following your majority religion.

**Comment by Infixo** [comment]
Those Qadi effects will not be visible to the player when looking at yields in the city. The AI won't care because it is a UB and it will be produced anyway.

**Comment by Hokath** [comment]
jizya could be changed to use the existing code for yield per religion in the city. A bit different but has support.
The hospital converts food to science, doesnt it. Perhaps something there (maybe it needs to be generalised in the DLL) could be done for this and the Qila

**Comment by Infixo** [comment]
Hospital uses a particular table Building_ScienceFromYield. And whenever science yields are calculated in the code, there is an exception to handle that. Very bad design. Not to be reused easily, if ever.

**Comment by pineappledan** [comment]
hospital and hanse use the scienceFromYield table. It's a clunky implementation.  A table for YieldsFromPercentYields where you could define an InputYield and an OutputYield would have been much more elegant. 

Qila has Food -> Culture lua. Just have to adapt that to production -> culture instead. Should be straightforward

**Comment by Infixo** [comment]
The correct syntax is "if pUnit:IsMounted() then", wthout "Get"

**Comment by Infixo** [comment]
There are 2 Sofas now...

**Comment by pineappledan** [comment]
I deleted 1 of the sofa luas

**Comment by Infixo** [comment]
I reworked Sofa, all is ok now.

**Comment by pineappledan** [comment]
Still need last Qadi lua, not yet written

**Comment by Infixo** [comment]
Oh, so that is why somebody asked about Majority religion?
There is simply pPlayer:GetMajorityReligion(), it calls GetReligionInMostCities(). But check for NO_RELIGION (-1).
Also for cities there is: GetNumFollowers(ReligionTypes eReligion). Note that some citizens may be not religious at all, idk if this effect is for "followers but not your religion" or "anyone not following your religion, even if they don't follow any religion"

**Comment by pineappledan** [comment]
What I had planned was for something like:
Gold per turn= (TotalCityPopulation - PopulationFollowing(GetMajorityReligion(Player)))

**Comment by adaneslavo** [comment]
I asked for religion to Teutonic Order's Chapter promotion btw :P.

**Comment by Infixo** [comment]
Done.
