### ISSUE TITLE
Rework Maya: add new GameEvent

### ISSUE THREAD

**Issue by adaneslavo** [adaneslavo/More-Unique-Components-for-VP#53]

**Comment by adaneslavo** [comment]
```function OnEndOfMayaLongCount(iPlayer, iBaktun, iBaktunPreviousTurn)
   print("END OF MAYA LONG COUNT", iPlayer, iBaktun, iBaktunPreviousTurn)
end
GameEvents.PlayerEndOfMayaLongCount.Add(OnEndOfMayaLongCount)```

**Comment by pineappledan** [comment]
unrelated, but has anything been done regarding Hinin's comment about the k'atun ajaw promotions?

The intent was to have the k'atun ahaw level up every 20 turns of game time, but as they were implemented they marked 20 turns from the unit's creation. It should be possible to have a unit built on turn 99, and on turn 100 for it to get level 1 of the k'atun ajaw bonus

**Comment by adaneslavo** [comment]
No. Hinin is wronf and they take into acount GameTurns. I don't know why he thought about Unit turns. It was old abandoned idea I even didn't start implementing.

**Comment by adaneslavo** [comment]
I reapaired all bugs mentioned by @FoxOfWar. They will be implemented in v26.

**Comment by adaneslavo** [comment]
```
function OnGoodyHutReceivedBonus(iPlayer, iUnit, eGoody, iX, iY)
   dprint("OnGoodyHutReceivedBonus", iPlayer, iUnit, eGoody, iX, iY)
end
GameEvents.GoodyHutReceivedBonus.Add(OnGoodyHutReceivedBonus)
```

**Comment by pineappledan** [comment]
Update to VP is scheduled for tonight. Should be able to close this and the Baan Chang issues
