### ISSUE TITLE
Rework latifundium.

### ISSUE THREAD

**Issue by adaneslavo** [adaneslavo/More-Unique-Components-for-VP#55]

**Comment by pineappledan** [comment]
It now sounds to me like the easiest, most fair solution is the following:

- Latifundium takes a long time to build (15-25 turns on normal speed)
- On completion, immediately spawns a fig resource and plantation improvement on an adjacent tile, and claims that tile for Rome. 
- Latifundium cannot be removed or pillaged.
- Cannot build latifundium adjacent to each other. 
- Latifundium improves resources below it

Advantages:
- no delays or placeholders means no extra art assets
- no delays eliminates issues with savegame data, and storing fig placement/maturation on reloading.
- no delays means no complex timers, tile checking, maturation mechanics, or tile ownership checks
- no delays means no possibility for tile ownership to change between when a latifundium is constructed and the figs are completed
- no adjacency cuts down on total number of latifundia possible on map
- no adjacency means more varied landscapes (not just all purple plantations)
- Latifundium permanence means AI can't swap back and forth between plantation and latif.
- Latifundium permanence means AI can get plantations back

**Comment by adaneslavo** [comment]
Done.
