### ISSUE TITLE
Sukritact_ChangeResearchProgress

### ISSUE THREAD

**Issue by Infixo** [adaneslavo/More-Unique-Components-for-VP#60]
There are few cases of using Sukritact_ChangeResearchProgress.
This mechanism was created outside of CP to handle Science Overflow. I think CP can handle properly science overflow, so there should be no need to use that Lua.

So, if a tech is currently being researched use ChangeResearchProgressTimes100(TechTypes eIndex, int iChange, PlayerTypes ePlayer) and if not use Player.ChangeOverflowResearch(iChange).

Actually, probably the latter is enough because any overflow is added to a researched tech during research processing in player's turn.

**Comment by adaneslavo** [comment]
Changed for Holkan, Pitz and Madrasah. Used second function for all.
