### ISSUE TITLE
Unit creation sequence

### ISSUE THREAD

**Issue by Infixo** [adaneslavo/More-Unique-Components-for-VP#61]
When unit is created in the city (trained or purchased) 3 events are triggered:
1. UnitSetXY
2. UnitCreated
3. CityTrained

When unit is created not in the city 2 events are called:
1. UnitSetXY
2. UnitCreated

Please be careful of applying multiple effects. Affects: Monitor, Iron Chariot, Landwehr, Ballista, Seir Morb, Goedendag

**Comment by adaneslavo** [comment]
What changes do you suggest to reduce the overlapping job of them?

**Comment by Infixo** [comment]
Depends on situation. If an effect is to be apllied for units trained or purchesed in cities - use CityTrained. If an effect is to aplied to any unit created, no matter how - then use UnitCreated.

**Comment by Infixo** [comment]
I’d say default should be CityTrained, as this is the main source of units in game. UnitCreated only if really necessary.

**Comment by adaneslavo** [comment]
What about units gifted from city-states? Every unit could be trained of gifted from CS, so both function are always needed.

**Comment by pineappledan** [comment]
This also affects Yamato. 
I agree with Adan, UnitCreated sounds like it should be the natural default, since this captures events, policies, and CS gifts. 
Goedendag, for instance, could be created through the last authority policy without being trained.

**Comment by adaneslavo** [comment]
I suppose we cannot do anything with this to simplify it more. Closing issue.
