### ISSUE TITLE
Tersane lua unnecessary

### ISSUE THREAD

**Issue by pineappledan** [adaneslavo/More-Unique-Components-for-VP#63]
Tersane has a lua to give Prize Ships promotion to melee naval units trained in city. This can be done with 'TrainedFreePromotion' in sql. I have added to sql now, just want to verify that lua can be deleted.

Prize ship promotion can only be applied to UNITCOMBAT_NAVALMELEE, so there is no issue with applying directly to building.

is there any reason to keep the lua or can it be safely deleted?

**Comment by Infixo** [comment]
You can just test it to confirm.

**Comment by adaneslavo** [comment]
I checked table UniPromotion_UnitCombats and Prize Ships is not mentioned there. So it will be given to any unit produced in city with tersane even if it is broken on them. Lua is needed and you need to revert changes made o sql I think.

**Comment by Infixo** [comment]
No, no. You need to check if putting a combat into the table will prevent this promo for being granted to other combats than the ones mentioned in the table. If yes then lua is not needed, if no then it is needed.

**Comment by adaneslavo** [comment]
But first we need to check if putting this combat into table is not interering with current VP protmotion usage. I wanted to avoid changing that table.

**Comment by pineappledan** [comment]
Shouldn’t be a problem. The only other unit that has prize ships is the sea beggar, also navalmelee.

 I’ll test it tonight though

**Comment by pineappledan** [comment]
I tested this, and I was not able to get prize ships to be placed on naval melee units with SQL.
