### ISSUE TITLE
Babylon - Etemenanki purchase bonus triggers only if building is invested in same city

### ISSUE THREAD

**Issue by shbehna** [adaneslavo/More-Unique-Components-for-VP#70]
In the 4UC spreadsheet, Etemenanki yields 15% food/science output of the city as an instant yield when a building is purchased in ANY city. Currently, it only does that in the current city.

**Comment by adaneslavo** [comment]
That's how sql works. We will see what can be done: changed description or ability. Thx.

**Comment by pineappledan** [comment]
I think on empire would be better, since this is the wonder's "big effect"

**Comment by adaneslavo** [comment]
Added only for building.
Event for units is not responding.
[https://github.com/adaneslavo/More-Unique-Components-for-VP/commit/9222e9511447f52e3bb9b7ebe678a40cad5bd4c8](url)
