### ISSUE TITLE
Siam - Baan Chang (Elephant Camp) triggers for any unit spawn

### ISSUE THREAD

**Issue by shbehna** [adaneslavo/More-Unique-Components-for-VP#9]
The ability "Receive X in city every time a city state gifts a unit" triggers for any unit spawning. For example, purchases with gold and faith (event missionaries), unit created by events, and even unit upgrades.

**Comment by adaneslavo** [comment]
Working on it.

**Comment by adaneslavo** [comment]
Joined:
    Jan 9, 2016

Messages:
    1,446

Gender:
    Male

Location:
    Warsaw

    adan_eslavo said: ↑

        @Infixo do you know some event triggered by gifting unit from cs? I found one whe you gift them unit but it doesn't work the other way.

    There is that:
    Code:

 ```   // Event sent upon a City State giving a gift (v73)
    //   GameEvents.MinorGift.Add(function(iMinor, iMajor, iGift, iFriendshipBoost, 0, bFirstMajorCiv, false, szTxtKeySuffix) end)```

**Comment by Infixo** [comment]
The new event is GameEvents.MinorGiftUnit.Add(function(iMinor, iMajor, iUnitType) end)

**Comment by pineappledan** [comment]
Has this been resolved with the Jan 21 VP update?

**Comment by Infixo** [comment]
It is available in VP 1-21
