### ISSUE TITLE
Coimbra

### ISSUE THREAD

**Issue by Infixo** [adaneslavo/More-Unique-Components-for-VP#99]
New Feitoria always increases num of dummies. Is there a situation when the number of dummies would decrease? Pillage, new impovement instead of Feitoria, etc.

**Comment by pineappledan** [comment]
Also if a city with a feitoria is flipped to Portugal via conquest.

Would it not be easiest to check plot owner on all feitorias at end of turn??

**Comment by Infixo** [comment]
Checking ALL improvements every turn is not good from processing perspective. Event quickly filters out non-feitoria improvements, so it is much, much faster.
